# Generated by Django 2.2.5 on 2019-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191124_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(null=True, upload_to='posts_pics'),
        ),
    ]
