# Generated by Django 2.2.5 on 2019-11-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
