# Generated by Django 2.2.5 on 2019-11-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Comment'},
        ),
    ]
