# Generated by Django 2.2.5 on 2019-11-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191128_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='post_comment',
        ),
    ]
