# Generated by Django 2.2.5 on 2019-12-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20191215_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created',
        ),
    ]
