# Generated by Django 2.2.5 on 2019-12-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20191217_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('by', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Announcement',
                'ordering': ['-time'],
            },
        ),
    ]
