# Generated by Django 2.2.5 on 2019-12-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('classes_to_enrol', models.CharField(max_length=50)),
                ('time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Announcement',
                'ordering': ['-time'],
            },
        ),
    ]
