# Generated by Django 2.2.5 on 2019-12-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_enquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
