# Generated by Django 2.2.5 on 2019-12-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191216_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
    ]
