# Generated by Django 2.2.5 on 2019-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191216_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parent_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
