# Generated by Django 2.2.5 on 2019-12-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191217_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
    ]
