# Generated by Django 2.2.5 on 2019-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_staffprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
