# Generated by Django 2.2.5 on 2019-12-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191221_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
    ]
