# Generated by Django 2.2.5 on 2019-12-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_staffprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(default='media/download.jpg', upload_to=''),
        ),
    ]
