# Generated by Django 2.2.5 on 2019-12-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191224_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='posts_pics'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='profile_pix'),
        ),
    ]
