# Generated by Django 2.2.5 on 2019-12-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191227_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(default='download.jpg', upload_to='posts_pics'),
        ),
    ]
