# Generated by Django 2.2.5 on 2019-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancy',
                'ordering': ['-created_at'],
            },
        ),
    ]
