# Generated by Django 2.2.5 on 2019-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='Cv')),
                ('years_of_experience', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
