# Generated by Django 2.2.5 on 2019-12-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_auto_20191206_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
