# Generated by Django 2.2.5 on 2019-12-21 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20191215_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='applications',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
    ]
