# Generated by Django 2.2.5 on 2019-12-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20191221_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
