# Generated by Django 2.2.5 on 2019-12-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_auto_20191221_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='email',
        ),
    ]
