# Generated by Django 2.2.5 on 2019-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_remove_applications_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
    ]
