# Generated by Django 2.2.5 on 2019-12-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0009_applications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
