# Generated by Django 2.2.5 on 2019-12-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_auto_20191221_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='email',
        ),
    ]
