# Generated by Django 2.2.5 on 2019-12-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_auto_20191221_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vacancy'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
