# Generated by Django 2.2.5 on 2019-12-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_auto_20191221_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='email',
        ),
    ]
