# Generated by Django 2.2.5 on 2019-12-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0016_applications_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='cv',
        ),
    ]
