# Generated by Django 2.2.5 on 2019-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0017_remove_applications_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
