# Generated by Django 2.2.5 on 2019-12-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0019_auto_20191222_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
