# Generated by Django 2.2.5 on 2019-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0020_delete_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('post', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('years_of_experience', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('vacancy', models.ForeignKey(default='', on_delete='', to='vacancy.Vacancy')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
