# Generated by Django 2.2.5 on 2019-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0021_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
