# Generated by Django 2.2.5 on 2019-12-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0023_auto_20191222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='vacancy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy'),
        ),
    ]
