# Generated by Django 2.2.5 on 2019-12-23 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0025_applications_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
