# Generated by Django 2.2.5 on 2019-12-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0026_applications_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
