# Generated by Django 2.2.5 on 2019-12-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0027_auto_20191222_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=300)),
                ('job_description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('post', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('years_of_experience', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
                ('vacancy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy')),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
